XPATHS = {
    "i_username": '//*[@id="branding-username"]',
    "i_password": '//*[@id="branding-password"]',
    "b_submit": '//*[@id="branding-sumbit-button"]',
    "b_hello_prompt": "/html/body/div[5]/div[4]/div/div/div/span[2]/span[2]/button[1]",
    "b_student_tour": "/html/body/div[5]/div[4]/div/div/div/span[2]/span[2]/button",
    "l_calculus": "/html/body/div[4]/span/span/div/div/div/div/div/ul/li[3]/ul/li[1]/a",
    "l_composition": "/html/body/div[4]/span/span/div/div/div/div/div/ul/li[3]/ul/li[2]/a",
    "l_creative_arts": "/html/body/div[4]/span/span/div/div/div/div/div/ul/li[3]/ul/li[3]/a",
    "l_french": "/html/body/div[4]/span/span/div/div/div/div/div/ul/li[3]/ul/li[4]/a",
    "l_new_student_orientation": "/html/body/div[4]/span/span/div/div/div/div/div/ul/li[3]/ul/li[5]/a",
    "l_access_pearson": "/html/body/div[3]/div[2]/div[2]/div[2]/div/nav/ul/li[13]/a",
    "b_open_pearson": '//button[contains(.,"\n                    Open Pearson\n                ")]',
    "b_accept_cookies": '//*[@id="onetrust-accept-btn-handler"]',
    "l_calculus_all_assignments": '//*[@id="58050"]',
    "b_nav_courses": '//*[@id="global_nav_courses_link"]',
    "l_composition_grades": '//ul[@id="section-tabs"]/li[5]/a',
    "l_creative_arts_grades": '//*[@id="section-tabs"]/li[5]/a',
    "l_elementary_french": '//*[@id="nav-tray-portal"]/span/span/div/div/div/div/div/ul/li[3]/ul/li[4]/a',
    "l_elementary_french_grades": '//*[@id="section-tabs"]/li[6]/a',
    "l_NSO": '//*[@id="nav-tray-portal"]/span/span/div/div/div/div/div/ul/li[3]/ul/li[5]/a',
    "l_NSO_grades": '//*[@id="section-tabs"]/li[5]/a',
    "i_course_name": '//*[@id="course_select_menu"]',
}
